Update to use latest librespot from GithHub repo
oSumAtrIX/DownOnSpot pull request #105
Opened 2024-09-08 11:27 UTC by grufkork

With this I changed the librespot dependency to pull directly from Librespot's Github repo. After some changes I can successfully download songs again. There's some small interface changes that I'll highlight below, as I'm not sure how to handle them.

I've not fixed track relinking yet, but I'll look into that in a moment.

Using a live git repo as a dep is probably not the greatest idea, but Librespot does not publish any packages, so maybe pin it to a specific commit or make a fork? I suppose you might want to fork regardless to provide free account support, if that is still of importance.

2024-09-08 11:34 UTC, grufkork reviewed
Here's the things that need to be looked at. I also haven't tested any features other than downloading a 5-song playlist as 320kbps mp3's.

As always, thanks for the great program! ❤️

2024-09-08 11:34 UTC, grufkork commented on src/downloader.rs
> +                    // TODO: figure out if available
Track relinking needs to be reimplemented

2024-09-08 11:34 UTC, grufkork commented on src/downloader.rs
>  			track = DownloaderInternal::find_alternative(session, track).await?;
Track relinking

2024-09-08 11:34 UTC, grufkork commented on src/downloader.rs
> +				FileFormat::AAC_48,  // TODO
The AAC_[bitrate] formats have been removed in favour of what I assume are bit depths. Is this a good mapping, or should there be a new quality option added?

2024-09-08 11:34 UTC, grufkork commented on src/main.rs
> +impl From<librespot::core::error::Error> for SpotifyError {
This `impl` maybe should be moved to a more relevant place

2024-09-08 11:34 UTC, grufkork commented on src/downloader.rs
> -			FileFormat::MP4_128_DUAL => Self::Mp4,
Some formats have been removed. I have not got the faintest if that is of any importance

2024-09-08 11:34 UTC, grufkork commented on src/downloader.rs
> +            FileFormat::FLAC_FLAC => Self::Unknown
Flac has been added, is this relevant? I don't think Spotify provides any Flacs yet, likely just a placeholder.

2024-09-08 11:34 UTC, grufkork commented on Cargo.toml
> +librespot = { git = "https://github.com/librespot-org/librespot" }
This dependency should be changed

2024-09-08 12:11 UTC, grufkork commented on src/downloader.rs
> +                    // TODO: figure out if available
On further investigation, it seems the track relinking is handled automatically when the market is set. Neither `Availability` or `Alternatives` yield anything, neither for a track I know is relinked ([this](https://open.spotify.com/track/7lds8jOEJM9d72i0A0YEfX) to [this](https://open.spotify.com/track/0nnJQKZZAayaO9L9CyE1i8)) and for a (track that has been completely removed)[https://open.spotify.com/track/6ZVegummYvkbBaEshdZMCP?si=e902e8622f6148e6). So seemingly this can just be ignored

2024-09-08 15:36 UTC, oSumAtrIX requested changes

2024-09-08 15:36 UTC, oSumAtrIX commented on Cargo.toml
> +librespot = { git = "https://github.com/librespot-org/librespot" }
To?

2024-09-08 15:36 UTC, oSumAtrIX commented on src/downloader.rs
> +                    // TODO: figure out if available
What's the problem with implementing it? Check if it is implemented by default. In case it is , related code and the json config should be removed.

2024-09-08 15:36 UTC, oSumAtrIX commented on src/downloader.rs
> -			FileFormat::MP4_128_DUAL => Self::Mp4,
The formats can be removed if they do not exist anymore. I had once bumped to late librespot versions and I did it too.

2024-09-08 15:36 UTC, oSumAtrIX commented on src/downloader.rs
> +            FileFormat::FLAC_FLAC => Self::Unknown
It should be added. All formats should be mapped.

2024-09-08 15:36 UTC, oSumAtrIX commented on src/downloader.rs
> +				FileFormat::AAC_48,  // TODO
MP3 320kbit is max 20khz. I am not sure where AAC_24 belongs though...maybe GPT could suggest a mapping? The alternative solution is to simply allow downloading the formats.

2024-09-08 15:36 UTC, oSumAtrIX commented on src/main.rs
> +impl From<librespot::core::error::Error> for SpotifyError {
To error.rs?

2024-09-08 20:52 UTC, grufkork commented on src/downloader.rs
> +                    // TODO: figure out if available
Alright, looks like I got it working albeit crudely. The `is_available` function has disappeared thus complicating the matter. In general I think users should be strongly advised to set a market, as this part of the API seems to be built under the assumption that a market is selected. 

Only problem is I'm not sure how to determine whether a track is available or not. Currently I simply switch tracks if there is an alternative that in turn does not have any alternatives. The availability field does not seem to do much. This however I have no idea if it is fool-proof or not, as there might be linked tracks that in turn are completely unavailable. The way to check if a track is available now seems to be to try to actually fetch it and see if it fails, at which point you could try to replace it, but due to the lack of documentation from both Librespot and Spotify I do not know if this can create circular loops. You could add checks to not try the same track multiple times, but at that point it is getting very complicated to implement a feature that Spotify already implements correctly when you choose a market. 

I'll push the code in a moment, but I'm not sure if I should keep it in. It might very well be so that it will relink some tracks that are already downloadable to tracks that then are not downloadable, so it actually causes harm in some edge cases. But again, I simply do not know enough of the fields (which don't appear to have an equivalent in the official API) to understand it.

2024-09-08 20:55 UTC, grufkork commented on src/main.rs
> +impl From<librespot::core::error::Error> for SpotifyError {
Of course, found it :P

2024-09-08 21:03 UTC, grufkork commented on Cargo.toml
> +librespot = { git = "https://github.com/librespot-org/librespot" }
Lock file *should* be enough but it's more understandable to pin it manually, done

2024-09-08 21:07 UTC, grufkork commented on src/downloader.rs
> +				FileFormat::AAC_48,  // TODO
I believe the numbers concern bit depth, so there isn't really a 1:1 mapping. But with the way the fallbacks work, I think this is a good/intuitive solution.

2024-09-09 22:56 UTC, oSumAtrIX commented
I received a Cease & Desist letter from Spotify and will discontinue this repository immediately. I am sorry for your efforts on this PR, though, and thank you for your contribution to DownOnSpot.

2024-09-09 22:56 UTC, closed without merging