format code and add argument parser
oSumAtrIX/DownOnSpot pull request #14
Opened 2022-01-19 16:00 UTC by breuerfelix

Signed-off-by: Felix Breuer <fbreuer@pm.me>

2022-01-19 18:05 UTC, oSumAtrIX commented on src/downloader.rs
> +			return Err(SpotifyError::AlreadyDownloaded);
Should this really return an error? Maybe we should silently skip the download.

2022-01-20 10:46 UTC, breuerfelix commented on src/downloader.rs
> +			return Err(SpotifyError::AlreadyDownloaded);
this is how i implemented it in the first place but it required some function signature changes to propagate it to the top which looked a little more ugly in the code, cause the function returned also a bool values which was called `downloaded`.

if you know a better way on how to silently return, it would be perfect :)

2022-02-05 02:56 UTC, oSumAtrIX commented
Almost ready to get merged. We just need to look into the argument parser a bit more since it is kinda just dangling at the beginning of the method. Separating the code to a new file might be useful to handle arguments.

2022-03-02 13:08 UTC, oSumAtrIX commented
Can you split this PR so we have a separate PR for the argument parser and skipping downloads? I would like to merge the later

2022-05-18 18:25 UTC, sraka1 commented
@oSumAtrIX is this being worked on?

2022-06-07 08:08 UTC, breuerfelix commented
well it is done and working, i just do not have the time in splitting this into two seperate PRs
i can rebase it though, if you wanna merge it in one PR (it is split into different commits tho)

2022-06-17 06:49 UTC, varac commented
Looking forward to this feature !

2022-11-27 08:54 UTC, mossepso requested changes

2022-11-27 08:54 UTC, mossepso commented on .gitignore
> +shell.nix
For things like this, you can use the file in your project directory at `.git/info/exclude` it works just like .gitignore, but it is a private file just for you.

2022-11-27 08:54 UTC, mossepso commented on Cargo.toml
> +librespot = "0.3.1"
This seems like a change for yourself rather than one to commit to the project. 

Also the readme mentions `librespot = "0.4.2"`, not `0.3.1` at the moment.

But I don't think you'd want to commit this.

2022-11-27 08:55 UTC, mossepso commented
Very useful feature! I will be using the fork for a bit in order to see if it works.

2022-12-01 08:45 UTC, breuerfelix commented
@oSumAtrIX if you plan on merging this, i can rebase and update the branch :) just let me know

2022-12-01 10:25 UTC, oSumAtrIX requested changes

2022-12-01 11:44 UTC, breuerfelix commented
haha :D the problem is, that this PR is (until today) my first and only touching point with rust... so i am not that good at rust and i also don't know all these best practices or how to implement them. for example, i thought you use the unwrap_or function to set default values. that means, i have no clue on how to do this in another way :D

so: i can rebase this pr but i am not able to implement your changes, maybe someone else can fix them or maybe we can merge my pr to a branch for you as a starting point so you can refactor this a little bit :)

2024-09-09 22:56 UTC, oSumAtrIX commented
I received a Cease & Desist letter from Spotify and will discontinue this repository immediately. I am sorry for your efforts on this PR, though, and thank you for your contribution to DownOnSpot.

2024-09-09 22:56 UTC, closed without merging