Avoid crashing on local tracks
oSumAtrIX/DownOnSpot pull request #88
Opened 2024-06-25 03:49 UTC by 0xNF

Tracks with no id will crash the application (#84).

This PR fixes this by making the Download of a track with is_local or a None id into an error download. This causes DownOnSpot to correctly report the error, skip over the track, and continue without crashing.

This fix is a modification of the edit suggested by @Daprussiaduck

Closes #84

2024-06-25 20:09 UTC, oSumAtrIX requested changes
I think instead of causing an error, local tracks should be filtered away. Ideally wherever `from` is used

2024-06-28 03:45 UTC, 0xNF commented
I moved the local check into downloader.rs:

```rust
/// Add URL or URI to queue
	pub async fn add_uri(&self, uri: &str) -> Result<(), SpotifyError> {
		let uri = Spotify::parse_uri(uri)?;
		let item = self.spotify.resolve_uri(&uri).await?;
		match item {
			SpotifyItem::Track(t) => {
				if t.id.is_some() && !t.is_local {
					self.add_to_queue(t.into()).await;
				}
			}
			SpotifyItem::Album(a) => {
				let tracks = self.spotify.full_album(&a.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}
			SpotifyItem::Playlist(p) => {
				let tracks = self.spotify.full_playlist(&p.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}
			SpotifyItem::Artist(a) => {
				let tracks = self.spotify.full_artist(&a.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}

			// Unsupported
			SpotifyItem::Other(u) => {
				error!("Unsupported URI: {}", u);
				return Err(SpotifyError::Unavailable);
			}
		};
		Ok(())
	}
```

2024-06-29 19:48 UTC, oSumAtrIX commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
Can albums be even local? How about Artist tracks in line 114? I thought you could only create playlists with local songs.

2024-06-30 02:40 UTC, 0xNF commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
no, probably not. I was just covering my bases, really. I can strip the check there if you'd like.

2024-07-03 14:20 UTC, oSumAtrIX commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
Please do so and keep the is_local check only where necessary.

2024-07-10 06:00 UTC, 0xNF commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
I removed the checks from the non-track branches. After thinking about it, I decided to ignore the `is_local` check in favor of just checking that the track has an id via `track.id.is_some()`. My thinking is that, is_local implies id.is_none, but id.is_none might not imply is_local, and in all cases no id would be an invalid download.

2024-07-10 23:51 UTC, oSumAtrIX commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
Isn't just checking for is_local enough?

2024-07-11 01:33 UTC, 0xNF commented on src/downloader.rs
> +					.filter(|t| t.id.is_some() && !t.is_local)
Your call. I'm fine with just doing the is_local check. Since the code is structured to use Option<String> for the track id, I was leaning more into that, but is_local is probably sufficient. The latest push removes the is_some check and includes only the is_local check.

2024-07-11 02:03 UTC, oSumAtrIX approved these changes

2024-07-11 02:04 UTC, merged

2024-07-11 02:04 UTC, oSumAtrIX commented
Thanks!